<?php

/**
 * Created by PhpStorm.
 * User: LC
 * Date: 22/01/2017
 * Time: 16:29
 */
require_once standart_path.'web/core/Page.php';
require_once standart_path.'server_script/Register/Register.php';
require_once standart_path.'core/file/FileHandler.php';
require_once standart_path.'core/database/Runner.php';
class ConfirmationPage extends Page
{
    private $data, $map;
    protected function head(bool $navigation = false)
    {
        if(filter_input(INPUT_GET, Register::SECURITY_TOKEN) === null) {
            header("HTTP/1.0 404 Not Found - command not found", true, 404);
            exit();
        }
        $security_token = filter_input(INPUT_GET, Register::SECURITY_TOKEN);
        $this->map = md5($security_token);
        try {
            $fh = new FileHandler(REGISTRATION_TEMPORARY_PATH."/".$this->map, "r");
            $data = "";
            for($i = $fh->begin(4096); $i != $fh->end(); $fh->next($i)) $data .= $i;
            $this->data = json_decode($data);
        } catch (Exception $e) {
            header("HTTP/1.0 404 Not Found - command not found", true, 404);
            exit();
        }
        parent::head($navigation); // TODO: Change the autogenerated stub
    }

    protected function bodyPage()
    {
        // TODO: Implement bodyPage() method.
        //echo "<div>";
        //echo "<div>";
        echo "<div style='text-align: center;'>";
        echo "<h1>";
        try {
            $id = $this->data[1];
            $username = $this->data[2];
            $email = $this->data[3];
            $password = $this->data[4];
            $runner = new Runner();
            $runner->connect(host, port, database, database_username, database_password);
            $insert = new Insert('benutzer');
            $insert->append_column_value('id', new Parameter($insert->getParameterVariableIntegerOrder(), $id));
            $insert->append_column_value('username', new Parameter($insert->getParameterVariableIntegerOrder(), $username));
            $insert->append_column_value('email', new Parameter($insert->getParameterVariableIntegerOrder(), $email));
            $insert->append_column_value('pass', new Parameter($insert->getParameterVariableIntegerOrder(), $password));
            $runner->append_query($insert);
            //$runner->execute();
            echo "Account has been confirmed, you can login";
        } catch(Exception $e) {
            echo $e->getMessage();
        }
        echo "</h1>";
        echo "</div>";
        //echo "</div>";
        //echo "</div>";
    }
}
